source 'https://rubygems.org'
ruby '2.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

# This gem removes middlewares we don't need on the api controllers
gem 'rails-api'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# BE gems
gem 'finance'

# FE gems
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'backbone-on-rails'
gem 'handlebars_assets'

# Application server
gem 'puma'

# Heroku deployment
gem "rack-timeout"
gem 'rails_12factor', group: :production

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '~> 4.0'
end

group :development do
  gem 'guard'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'rack-livereload'
end

